##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
   TAG_VALUE: "${{ github.event.inputs.tag }}"

stages:

  ## The first stage of actions
  Default:
    actions:
      #
      # Quality Checks for changelog
      #
      - type: liquibase
        command: checks run
        cmdArgs: {checks-scope: changelog}
      #
      # Review pending changes
      #
      - type: liquibase
        command: updateSQL
      #
      # Tag the database
      #
      - type: liquibase
        command: tag
        cmdArgs: { tag: "${TAG_VALUE}" }
      #
      # Update the database
      #
      - type: liquibase
        command: update
      #
      # Validate rollback
      #
      - type: liquibase
        command: rollbackSQL
        cmdArgs: { tag: "${TAG_VALUE}" }
      #
      #
      # Execute rollback
      #
      - type: liquibase
        command: rollback
        cmdArgs: { tag: "${TAG_VALUE}" }
      #
      # Update the database
      #
      - type: liquibase
        command: update

## do these actions after all flow commands, regardless of whether the above commands were successful
endStage:
  actions:
    - type: liquibase
      command: history