# This is a basic workflow to help you get started with Actions

name: rollback_changes

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
   inputs:
     tag:
       description: 'Enter tag to rollback'
       required: true
       
env:
    LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}
    LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_COMMAND_URL }}
    LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_COMMAND_USERNAME }}
    LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_COMMAND_PASSWORD }}
    LIQUIBASE_COMMAND_CHANGELOG_FILE: ${{ secrets.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
    LIQUIBASE_COMMAND_TAG: ${{ github.event.inputs.tag }}
    
jobs:

  Build_Job:
    runs-on: ubuntu-latest
    environment: 
      name: DEV

    steps:
    - uses: actions/checkout@v3
    
    - name: Rolling back DEV changes
      uses: docker://liquibase/liquibase
      with:
        args: rollback

    - name: Running history command 
      uses: docker://liquibase/liquibase
      with:
        args: liquibase history
    
  Test_Job:
    needs: Build_Job
    runs-on: ubuntu-latest
    environment: 
      name: TEST

    steps:
    - uses: actions/checkout@v3
    
    - name: Rolling back TEST changes
      uses: docker://liquibase/liquibase
      with:
        args: rollback

    - name: Running history command 
      uses: docker://liquibase/liquibase
      with:
        args: liquibase history

  Deploy_Prod_Job:
    needs: Test_Job
    runs-on: ubuntu-latest
    environment: 
      name: PROD

    steps:
    - uses: actions/checkout@v3
    
    - name: Rolling back PROD changes
      uses: docker://liquibase/liquibase
      with:
        args: rollback

    - name: Running history command 
      uses: docker://liquibase/liquibase
      with:
        args: liquibase history
